changelog-file:  changelogs/changelog.xml

url: jdbc:mysql://localhost:3306/transport_company
liquibase.command.username: root
liquibase.command.password: mysql_pass_123

#classpath: mysql-connector-j-9.4.0.jar
log-level: INFO
contexts: dev

#custom properties
parameter.AUTHOR_NAME: kiril_yotov
