status = warn

appender.console.type = Console
appender.console.name = Console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{HH:mm:ss.SSS} %-5p [%t] %c - %m%n

rootLogger.level = info
rootLogger.appenderRefs = console
rootLogger.appenderRef.console.ref = Console

logger.hibernate.name = org.hibernate.SQL
logger.hibernate.level = debug

logger.jdbc-bind.name = org.hibernate.orm.jdbc.bind
logger.jdbc-bind.level = trace